--CONSULTAS PCVENTAS
use pcventas
go
-- 1. LISTAR A LOS CLIENTES CUYO CODIGO ES C0005
--GUARDARLO COMO Q_EJERCICIO01
select * from facturas
where
idcliente like 'C0005'
go
--vista
Create view Q_Ejercicio01
as
select * from facturas
where
idcliente like 'C0005'
go
--2. LISTAR IDARTICULO, NOMARTICULO, STOCK, NOMBRE
-- DE LA TABLA ARTICULOS  Y CATEGORIA CUYO
-- NOMBRE DE CATEGORIA ES MULTIMEDIA
--guardarlo como q_ejercicio02
SELECT A.IDARTICULO,A.NOMARTICULO,A.STOCK,
C.NOMBRE FROM ARTICULOS  A INNER JOIN CATEGORIAS C
ON A.Categ = C.Categoria 
WHERE C.NOMBRE LIKE 'MULTIMEDIA'
GO
--view
create view q_ejercicio02
as
SELECT A.IDARTICULO,A.NOMARTICULO,A.STOCK,
C.NOMBRE FROM ARTICULOS  A INNER JOIN CATEGORIAS C
ON A.Categ = C.Categoria 
WHERE C.NOMBRE LIKE 'MULTIMEDIA'
GO
-- 3. LISTAR LAS FACTURAS EMITIDAS EL 14 DE AGOSTO DEL 2002
-- SE DEBEN MOSTRAR 4 REGISTROS
-- SE DEBE GUARDAR COMO CONSULTA1
SELECT F.IDFACTURA, C.NOMCLIENTE, C.EMAIL,F.FECHA
FROM FACTURAS F INNER JOIN CLIENTES C
ON F.IdCliente = C.Idcliente
Where F.FECHA ='2002-08-14'
GO
--VIEW
CREATE VIEW Consulta1
as
SELECT F.IDFACTURA, C.NOMCLIENTE, C.EMAIL,F.FECHA
FROM FACTURAS F INNER JOIN CLIENTES C
ON F.IdCliente = C.Idcliente
Where F.FECHA ='2002-08-14'
GO
-- 4 LISTAR LOS DETALLE DESPACHADOS DE LA FACTURA 10325
--GUARDAR COMO CONSULTA2

SELECT D.IDFACTURA,A.NOMARTICULO,D.CANTIDAD,D.PREVENTA
FROM DETALLES D INNER JOIN ARTICULOS A
ON D.IdArticulo = A.IdArticulo
WHERE D.IdFactura =10325
GO



--VIEW
CREATE VIEW Consulta2 
as
SELECT D.IDFACTURA,A.NOMARTICULO,D.CANTIDAD,D.PREVENTA
FROM DETALLES D INNER JOIN ARTICULOS A
ON D.IdArticulo = A.IdArticulo
WHERE D.IdFactura = 10325
GO
-- 5. LISTAR IDARTICULO,NOMARTICULO,STOCK DE LA TABLA ARTICULOS
--CUYO STOCK SEA MENOR DE 20
--GUARDE LA CONSULTA COMO qEjercicio03
SELECT A.IDARTICULO,A.NomArticulo,A.Stock
FROM ARTICULOS A
WHERE A.Stock <20
GO
--VIEW
CREATE VIEW qEjercicio03
as
SELECT A.IDARTICULO,A.NomArticulo,A.Stock
FROM ARTICULOS A
WHERE A.Stock <20
GO



-- 6. LISTAR LAS FACTURAS IDFACTURA,NOMCLIENTE Y FECHA
--DE LA TABLA FACTURAS CUYA FECHA ESTE
--ENTRE 1-12-2000 Y 31-12-2000
--GUARDAR COMO qEjercicio04
SELECT F.IdFactura,C.NOMCLIENTE,F.FECHA 
FROM Facturas F INNER JOIN Clientes C
ON F.IdCliente = C.Idcliente
WHERE F.FECHA BETWEEN '2000-12-01' AND '2000-12-31'
GO
--VIEW
CREATE VIEW qEjercicio04
as
SELECT F.IdFactura,C.NOMCLIENTE,F.FECHA 
FROM Facturas F INNER JOIN Clientes C
ON F.IdCliente = C.Idcliente
WHERE F.FECHA BETWEEN '2000-12-01' AND '2000-12-31'
GO
-- 7. LISTAR LAS FACTURAS EMITIDAS ANTES DEL AÑO 2000.
-- IDFACTURA, NOMCLIENTE, EMAIL, FECHA
--SE DEBEN MOSTRAR 53 REGISTROS
--GUARDAR COMO CONSULTA3
SELECT F.IDFACTURA, C.NOMCLIENTE, C.EMAIL, F.FECHA
FROM FACTURAS F INNER JOIN CLIENTES C
ON F.IDCLIENTE = C.IDCLIENTE
WHERE F.FECHA < '2000-01-01'
GO
--view
CREATE VIEW Consulta3
as
SELECT F.IDFACTURA, C.NOMCLIENTE, C.EMAIL, F.FECHA
FROM FACTURAS F INNER JOIN CLIENTES C
ON F.IDCLIENTE = C.IDCLIENTE
WHERE F.FECHA < '2000-01-01'
GO
-- 8. LISTAR LOS ARTICULOS CUYO STOCK SE ENCUENTRE DE 50 A 100 UNIDADES
-- SE DEBEN MOSTRAR 14 REGISTROS
-- IDARTICULO, NOMARTICULO, STOCK, NOMBRE DE CATEGORIA
-- GUARDARLO COMO CONSULTA4
SELECT A.IDARTICULO, A.NOMARTICULO, A.STOCK, C.NOMBRE
FROM Articulos A INNER JOIN Categorias C
ON A.Categ = C.Categoria
WHERE A.Stock BETWEEN 50 AND 100
go
--VIEW
CREATE VIEW	Consulta4
as
SELECT A.IDARTICULO, A.NOMARTICULO, A.STOCK, C.NOMBRE
FROM Articulos A INNER JOIN Categorias C
ON A.Categ = C.Categoria
WHERE A.Stock BETWEEN 50 AND 100
go
-- 9. LISTAR LAS FACTURAS EMITIDAS del 10 al 15 DE ENERO DEL 2002
-- SE DEBEN MOSTRAR 7 REGISTROS
-- GUARDAR COMO CONSULTA5
-- IDFACTURA, NOMCLIENTE,EMAIL, FECHA
SELECT F.IDFACTURA, C.NOMCLIENTE, C.EMAIL, F.FECHA
FROM FACTURAS  F INNER JOIN CLIENTES C
ON F.IdCliente = C.Idcliente
WHERE F.Fecha BETWEEN '2002-01-10' AND '2002-01-15'
GO
-- VIEW
CREATE VIEW Consulta5
as
SELECT F.IDFACTURA, C.NOMCLIENTE, C.EMAIL, F.FECHA
FROM FACTURAS  F INNER JOIN CLIENTES C
ON F.IdCliente = C.Idcliente
WHERE F.Fecha BETWEEN '2002-01-10' AND '2002-01-15'
GO
-- 10. LISTAR A LOS CLIENTES CUYO NOMCLIENTE
-- INICIE CON LA LETRA A
-- IDCLIENTE, NOMCLIENTE, EMAIL
SELECT IDCLIENTE, NOMCLIENTE, EMAIL
FROM CLIENTES
WHERE NOMCLIENTE LIKE 'A%'
GO
--VIEW
CREATE VIEW QEjercicio05
as
SELECT IDCLIENTE, NOMCLIENTE, EMAIL
FROM CLIENTES
WHERE NOMCLIENTE LIKE 'A%'
GO
-- 11. LISTAR LOS ARTICULOS CUYO NOMARTICULO CONTENGA MB
-- IDARTICULO, NOMARTICULO, STOCK
-- 6 REGISTROS
-- QEJERCICIO06
SELECT IDARTICULO,NOMARTICULO, STOCK
FROM Articulos
WHERE NomArticulo LIKE '%MB%'
GO
-- VIEW
CREATE VIEW QEjercicio06
as
SELECT IDARTICULO,NOMARTICULO, STOCK
FROM Articulos
WHERE NomArticulo LIKE '%MB%'
GO
-- 12 LISTAR LOS CLIENTES CUYO 3 CARACTER
--DE SU NOMBRE SEA LA D
-- IDCLIENTE,NOMCLIENTE,EMAIL
-- QEJERCICIO07
select * from Clientes 
where NomCliente like '___d%'
go
--view
create view QEjercicio09
as
select * from Clientes 
where NomCliente like '___d%'
go
--13 LISTAR LOS CLIENTES CUYO EMAIL
-- TENGA UN PROVEEDOR DEL PERU
-- 36 REGISTROS
--CONSULTA6
--
SELECT *  FROM CLIENTES
WHERE EMAIL LIKE '%.PE'
go
--view
Create view Consulta6
as
SELECT NomCliente  FROM CLIENTES
WHERE EMAIL LIKE '%.PE'
go
--- 14 LISTAR A LOS CLIENTES CUYO APELLIDO SEA GARCIA
-- 7 REGISTROS
--GUARDAR COMO CONSULTA7
SELECT * FROM Clientes 
WHERE NomCliente LIKE '%GARCIA%'
GO
--VIEW
CREATE VIEW CONSULTA7
AS

SELECT * FROM Clientes 
WHERE NomCliente LIKE '%GARCIA%'
GO
--  15 LISTAR A LOS ARTICULOS CUYO IDARTICULO CONTENGA EN EL 4
-- CARACTER EL NUMERO 2
-- 10 REGISTROS
--GUARDAR COMO CONSULTA8
SELECT * FROM Articulos
WHERE IdArticulo LIKE '___2%'
GO
---VIEW 
CREATE VIEW CONSULTA8
AS
SELECT * FROM Articulos
WHERE IdArticulo LIKE '___2%'
GO
-- 16 LISTAR A LÑOS CLIENTES CUYO NOMBRE CONTENGA 3 O
-- MENOS CARACTERES
-- 6 REGISTROS
-- CONSULTA9
SELECT * FROM Clientes 
WHERE NomCliente LIKE '___ %'
GO
--VIEW
CREATE VIEW CONSULTA9
AS
SELECT * FROM Clientes 
WHERE NomCliente LIKE '___ %'
GO
---------------------CAMPOS CALCULADOS-----------------
-- 17
--QEJERCICIO08
SELECT  PREARTICULO,FORMAT((PreArticulo * 0.10),'####.00' ) AS  DESCUENTO,
 FORMAT(PREARTICULO - (PreArticulo * 0.10),'####.00') AS PRECIO_PUBLICO
FROM Articulos
go
--VIEW
CREATE VIEW Qejercicio08
as
SELECT  PREARTICULO,FORMAT((PreArticulo * 0.10),'####.00' ) AS  DESCUENTO,
 FORMAT(PREARTICULO - (PreArticulo * 0.10),'####.00') AS PRECIO_PUBLICO
FROM Articulos
go
---------------- VALIDACION DE CAMPOS -------------------------------
--18
-- LISTAR IDARTICULO, NOMARTICULO, PREARTIULO Y NOMBRE DE CATEGORIAS
-- GUARDAR COMO QEJERCICIO09
-- SI LOS ARTICULOS PERTENECEN A MULTIMEDIA ENTONCES TENDRA UN 30 DE
-- RECARGO DE GASTOS DE ENVIO, CASO CONTRARIO 0
-- qejercicio09
SELECT Articulos.IdArticulo, Articulos.NomArticulo, Categorias.Nombre,
IIf([Nombre]='Multimedia',30,0) AS Gastos_envío
FROM Categorias INNER JOIN Articulos ON Categorias.Categoria = Articulos.Categ;
--VIEW 
GO
CREATE VIEW QEjercicio09
AS
SELECT Articulos.IdArticulo, Articulos.NomArticulo, Categorias.Nombre,
IIf([Nombre]='Multimedia',30,0) AS Gastos_envío
FROM Categorias INNER JOIN Articulos ON Categorias.Categoria = Articulos.Categ;
go
-- 
--  19 CALCULAR EL MONTO PREVENTA * CANTIDAD DE DETALLES
-- CONSULTA10
SELECT PREVENTA, CANTIDAD ,PREVENTA * CANTIDAD AS MONTO
FROM Detalles
GO
CREATE VIEW CONSULTA10
AS
SELECT PREVENTA, CANTIDAD ,PREVENTA * CANTIDAD AS MONTO
FROM Detalles
GO
-- 20 DE LA CONSULTAR ANTERIOR AGREGAR DESCUENTO QUE ES 10% DEL MONTO
-- CONSULTA11
SELECT PREVENTA, CANTIDAD ,PREVENTA * CANTIDAD AS MONTO,
(PREVENTA * Cantidad) * 0.10 AS DESCUENTO
FROM Detalles
GO
CREATE VIEW CONSULTA11
AS
SELECT PREVENTA, CANTIDAD ,PREVENTA * CANTIDAD AS MONTO,
(PREVENTA * Cantidad) * 0.10 AS DESCUENTO
FROM Detalles
GO
--------------------CONSULTA DE TOTALES - AGRUPAMIENTO ---------------------------


-- 20 LISTAR EL TOTAL DE STOCK, CANTIDAD DE ARTICULOS DE CADA CATEGORIA
--Qejercicio10

SELECT C.Nombre,SUM(A.Stock) AS TOTAL_STOCK,COUNT(A.IdArticulo) AS
 Nro_Articulo FROM Articulos A JOIN Categorias C ON
A.Categ= C.Categoria
GROUP BY C.Nombre ORDER BY C.Nombre DESC
GO
-- VIEW
CREATE VIEW QEjercicio10
AS
SELECT C.Nombre,SUM(A.Stock) AS TOTAL_STOCK,COUNT(A.IdArticulo) AS
 Nro_Articulo FROM Articulos A JOIN Categorias C ON
A.Categ= C.Categoria
GROUP BY C.Nombre 
GO
-- 21 LISTAR EL NOMBRE DE LOS CLIENTES Y LA CANTIDAD DE FACTURAS DE CADA UNO
--CONSULTA12
SELECT C.NOMCLIENTE , COUNT(F.IDFACTURA) AS FACTURAS__EMITIDAS
FROM CLIENTES C JOIN  Facturas F
ON C.Idcliente = F.IdCliente
GROUP BY C.NomCliente
GO
--VIEW
CREATE VIEW CONSULTA12
AS
SELECT C.NOMCLIENTE , COUNT(F.IDFACTURA) AS FACTURAS__EMITIDAS
FROM CLIENTES C JOIN  Facturas F
ON C.Idcliente = F.IdCliente
GROUP BY C.NomCliente
GO
-- 22 LISTAR EL MONTO DE CADA FACTURA(PREVENTAS * CANTIDAD)
-- DECADA FACTURA
-- CONSULTA13
select idfactura,sum(preventa * cantidad) as monto from Detalles
group by IdFactura
GO
--VIEW
create view Consulta13
as
select idfactura,sum(preventa * cantidad) as monto from Detalles
group by IdFactura
GO
---------------- USAR VISTAS DE OTRAS CONSULTAS
-- 23 LISTAR IDFACTURAS,NOMBRE DEL CLIENTE, FECHA Y
-- MONTO(PREVENTA  * CANTIDAD) DE DETALLES
--Q EJERCICIO11
SELECT F.IdFactura, C.NOMCLIENTE,F.FECHA,CON.monto FROM Facturas F JOIN Clientes C
ON F.IdCliente = C.Idcliente JOIN Consulta13 CON ON F.IdFactura = CON.IdFactura
ORDER BY F.IdFactura
go
--VIEW
CREATE VIEW QEjercicio11
as
SELECT F.IdFactura, C.NOMCLIENTE,F.FECHA,CON.monto 
FROM Facturas F JOIN  Clientes C
ON F.IdCliente = C.Idcliente JOIN Consulta13 CON ON
F.IdFactura = CON.IdFactura
go
-- 24 LISTAR EL NOMBRE DEL CLIENTE Y MONTO DESPACHADO(TOTAL DE PREVENTA * CANTIDAD) 



--USANDO VARIABLES EN CONSULTAS
DECLARE  @FECHA_CONSULTA DATETIME
SET @FECHA_CONSULTA = '1999-10-03'

SELECT * FROM FACTURAS
WHERE FECHA =@FECHA_CONSULTA




DECLARE  @NOMBRE_CATEGORIA VARCHAR(30)
SET @NOMBRE_CATEGORIA = 'COMPONENTES'

SELECT A.NomArticulo,C.NOMBRE
FROM ARTICULOS A JOIN Categorias C
ON A.Categ = C.Categoria
WHERE C.Nombre =@NOMBRE_CATEGORIA
GO
DECLARE  @NOMBRE_CATEGORIA VARCHAR(30)
SET @NOMBRE_CATEGORIA = 'COMPONENTES'
GO

DECLARE  @FECHA_INICIAL DATE,@FECHA_FINAL DATE 
SET @FECHA_INICIAL = '1999-10-03'
SET @FECHA_FINAL = '1999-10-04'

SELECT F.IdFactura, C.NOMCLIENTE,F.FECHA,CON.monto 
FROM Facturas F JOIN Clientes C
ON F.IdCliente = C.Idcliente JOIN Consulta13 CON ON F.IdFactura = CON.IdFactura
WHERE F.Fecha BETWEEN @FECHA_INICIAL AND @FECHA_FINAL
ORDER BY F.IdFactura
GO



---------------------------------------
CREATE PROCEDURE SP_FACTURA_FECHA(
@FECHA_INICIAL DATE,
@FECHA_FINAL DATE
)
AS
SELECT F.IdFactura, C.NOMCLIENTE,F.FECHA,CON.monto 
FROM Facturas F JOIN Clientes C
ON F.IdCliente = C.Idcliente JOIN Consulta13 CON ON F.IdFactura = CON.IdFactura
WHERE F.Fecha BETWEEN @FECHA_INICIAL AND @FECHA_FINAL
ORDER BY F.IdFactura
GO
--LLAMADO AL SP
EXECUTE  SP_FACTURA_FECHA '1999-10-03','1999-10-04'